### ISSUE TITLE
Shift Register examples do not compile on Arduino IDE 1.8.19

### ISSUE THREAD

**Issue by wongm** [tttapa/Arduino-Helpers#6]
I have been attempting to use the "BitBang" shift register implementation in this library, but I was getting compiler errors on Arduino IDE 1.8.19.

To see whether the issue is in my code, my dev setup, or something else, I have attempted to compile the example code found here:

https://github.com/tttapa/Arduino-Helpers/blob/master/examples/Arduino-Helpers/Hardware/Extended%20Input%20%26%20Output/2.%20Output/1.%20Shift%20Registers/2.BitBang-Blink/2.BitBang-Blink.ino

It fails with the following error:

```
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `begin':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:14: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:15: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:16: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `AH::BitArray<8u>::safeIndex(unsigned int) const':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `updateBufferedOutputs':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:24: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:32: undefined reference to `AH::ExtIO::shiftOut(unsigned int, unsigned int, unsigned char, unsigned char)'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/ShiftRegisterOut.ipp:35: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `setup':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\2.BitBang-Blink/2.BitBang-Blink.ino:47: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `loop':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\2.BitBang-Blink/2.BitBang-Blink.ino:53: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\2.BitBang-Blink/2.BitBang-Blink.ino:55: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `__base_ctor ':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/StaticSizeExtendedIOElement.hpp:21: undefined reference to `AH::ExtendedIOElement::ExtendedIOElement(unsigned int)'
C:\Users\Marcus\AppData\Local\Temp\ccC7ptqI.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\2.BitBang-Blink/2.BitBang-Blink.ino:43: undefined reference to `AH::ExtendedIOElement::pin(unsigned int) const'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Uno.
```

I receive similar error messages when compiling the SPI example as well.

https://github.com/tttapa/Arduino-Helpers/blob/master/examples/Arduino-Helpers/Hardware/Extended%20Input%20%26%20Output/2.%20Output/1.%20Shift%20Registers/1.SPI-Blink/1.SPI-Blink.ino

```
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `AH::SPIShiftRegisterOut<8u, SPIClass&>::updateBufferedOutputs()':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/SPIShiftRegisterOut.ipp:31: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/SPIShiftRegisterOut.ipp:39: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `AH::SPIShiftRegisterOut<8u, SPIClass&>::begin()':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/SPIShiftRegisterOut.ipp:21: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `AH::BitArray<8u>::safeIndex(unsigned int) const':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Containers/BitArray.hpp:79: undefined reference to `AH::fatalErrorExit()'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `setup':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\1.SPI-Blink/1.SPI-Blink.ino:42: undefined reference to `AH::ExtIO::pinMode(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `loop':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\1.SPI-Blink/1.SPI-Blink.ino:48: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\1.SPI-Blink/1.SPI-Blink.ino:50: undefined reference to `AH::ExtIO::digitalWrite(unsigned int, unsigned char)'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `_GLOBAL__sub_I_sreg':
C:\Documents\arduino\projects\libraries\Arduino_Helpers/AH/Hardware/ExtendedInputOutput/StaticSizeExtendedIOElement.hpp:21: undefined reference to `AH::ExtendedIOElement::ExtendedIOElement(unsigned int)'
C:\Users\Marcus\AppData\Local\Temp\ccRqjreq.ltrans0.ltrans.o: In function `_GLOBAL__sub_I_sreg':
C:\Documents\arduino\libraries\Arduino_Helpers\examples\Arduino-Helpers\Hardware\Extended Input & Output\2. Output\1. Shift Registers\1.SPI-Blink/1.SPI-Blink.ino:38: undefined reference to `AH::ExtendedIOElement::pin(unsigned int) const'
collect2.exe: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Uno.
```

Any ideas as to why both examples fail to compile on my machine?

**Comment by wongm** [comment]
And I've found my **answer** here:

https://forum.arduino.cc/t/undefined-reference-to-library-functions/956139/4

>  Recursive compilation of sketch source files is only done under the src subfolder:

I had initially installed the library in a subdirectory called `\libraries` of the `\projects` directory. The `\projects` should be up a level.

I had also installed the contents of the `src` directory into the  `\projects` directory, rather than the entire repository I downloaded from GitHub.

Installing the complete contents of the GitHub repository into a directory inside the correctly located `\projects` directory fixed my error.
